// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

/**
 * Greet returns a greeting for the given name
 */
export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(2659711170, name);
}

/**
 * IsProxyImportServerRunning reports whether the local import server is
 * currently listening.
 */
export function IsProxyImportServerRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(4024094468);
}

/**
 * SaveFile opens a native "Save As" dialog defaulting to filename, then
 * writes base64Data to the chosen path. This exists because the webview's
 * usual `<a download>`/blob-URL trick has no browser chrome to catch the
 * download in Wails' Linux webkit backend, so it silently does nothing.
 * Returns an error message on failure, or "" on success/cancel.
 */
export function SaveFile(filename: string, base64Data: string): $CancellablePromise<string> {
    return $Call.ByID(1396636678, filename, base64Data);
}

/**
 * StartProxyImportServer starts a local HTTP server that a chat site's
 * custom-endpoint chat requests can be pointed at, to import a character's
 * persona/scenario/greeting straight from an authenticated browser chat.
 */
export function StartProxyImportServer(): $CancellablePromise<string> {
    return $Call.ByID(3704819043);
}

/**
 * StopProxyImportServer stops the local import server, if running.
 */
export function StopProxyImportServer(): $CancellablePromise<string> {
    return $Call.ByID(265986365);
}
