// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

/**
 * FetchOllamaChat proxies a chat-completion request to a local/self-hosted
 * Ollama server from the Go backend rather than the webview's own fetch().
 * The webview's origin (e.g. wails://wails.localhost) isn't in Ollama's
 * default CORS allowlist, so a direct browser-side fetch to it gets a flat
 * 403 on the CORS preflight — a plain outgoing Go HTTP client has no
 * browser-side CORS to enforce, sidestepping the problem entirely.
 * 
 * Blocks for the whole request/response, emitting each NDJSON line as an
 * OllamaChatChunkEvent as it arrives so the existing live-token rendering
 * (see ai/ollama.ts) keeps working. The returned error becomes the JS-side
 * promise's rejection reason directly — no separate "done"/"error" event
 * needed, since the call itself only resolves once streaming is complete.
 * 
 * `ctx` is Wails' own per-call context (first-parameter convention — see
 * pkg/application/bindings.go's needsContext handling): calling `.cancel()`
 * on the CancellablePromise this returns to the frontend cancels `ctx`,
 * which aborts the underlying HTTP request via NewRequestWithContext. No
 * hand-rolled cancellation registry needed.
 */
export function FetchOllamaChat(requestID: string, url: string, bodyJSON: string, responseTimeoutSeconds: number): $CancellablePromise<void> {
    return $Call.ByID(3375761947, requestID, url, bodyJSON, responseTimeoutSeconds);
}

/**
 * IsProxyImportServerRunning reports whether the local import server is
 * currently listening.
 */
export function IsProxyImportServerRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(4024094468);
}

/**
 * SaveFile opens a native "Save As" dialog defaulting to filename, then
 * writes base64Data to the chosen path. This exists because the webview's
 * usual `<a download>`/blob-URL trick has no browser chrome to catch the
 * download in Wails' Linux webkit backend, so it silently does nothing.
 * Returns an error message on failure, or "" on success/cancel.
 */
export function SaveFile(filename: string, base64Data: string): $CancellablePromise<string> {
    return $Call.ByID(1396636678, filename, base64Data);
}

/**
 * SecretServiceDelete removes any stored passphrase (e.g. when the user
 * disables encryption or turns off "remember on this device"). Returns an
 * error message on failure, or "" on success — including when nothing was
 * stored to begin with.
 */
export function SecretServiceDelete(): $CancellablePromise<string> {
    return $Call.ByID(682201587);
}

/**
 * SecretServiceGet retrieves a previously-stored passphrase. Returns ("",
 * "") if nothing has been stored yet — that's an expected, non-error case
 * (e.g. first launch, or the user never opted into remembering it) — and
 * ("", errorMessage) for any other failure.
 */
export function SecretServiceGet(): $CancellablePromise<[string, string]> {
    return $Call.ByID(923299412);
}

/**
 * SecretServiceSet stores the passphrase in the OS credential store,
 * overwriting any previously-stored value. Returns an error message on
 * failure, or "" on success.
 */
export function SecretServiceSet(passphrase: string): $CancellablePromise<string> {
    return $Call.ByID(1374461064, passphrase);
}

/**
 * StartProxyImportServer starts a local HTTP server that a chat site's
 * custom-endpoint chat requests can be pointed at, to import a character's
 * persona/scenario/greeting straight from an authenticated browser chat.
 */
export function StartProxyImportServer(): $CancellablePromise<string> {
    return $Call.ByID(3704819043);
}

/**
 * StopProxyImportServer stops the local import server, if running.
 */
export function StopProxyImportServer(): $CancellablePromise<string> {
    return $Call.ByID(265986365);
}
