/** `window.go`/`window.runtime` only exist inside the Wails webview — a
 *  no-op check everywhere else (plain `pnpm dev`, tests, browsers), same
 *  idea as wailsConsoleForward.ts's `window.runtime` check.
 *
 *  These are hand-written wrappers around the Wails-injected globals rather
 *  than imports from the auto-generated `frontend/wailsjs/`: that directory
 *  is gitignored (regenerated by `wails build`/`wails dev`), but the Nix
 *  package builds the frontend with a plain `pnpm run build` that never
 *  invokes `wails generate`, so a build-time import from it would fail
 *  there even though `wails dev` works fine locally. */

interface WailsApp {
	StartProxyImportServer(): Promise<string>;
	StopProxyImportServer(): Promise<string>;
	IsProxyImportServerRunning(): Promise<boolean>;
	SaveFile(filename: string, base64Data: string): Promise<string>;
}

interface WailsRuntime {
	EventsOn(
		eventName: string,
		callback: (...data: unknown[]) => void
	): () => void;
	BrowserOpenURL(url: string): void;
}

function wailsApp(): WailsApp | undefined {
	return (window as unknown as { go?: { main?: { App?: WailsApp } } }).go
		?.main?.App;
}

function wailsRuntime(): WailsRuntime | undefined {
	return (window as unknown as { runtime?: WailsRuntime }).runtime;
}

export function isWailsDesktop(): boolean {
	return typeof window !== "undefined" && !!wailsApp();
}

export function startProxyImportServer(): Promise<string> {
	return wailsApp()!.StartProxyImportServer();
}

export function stopProxyImportServer(): Promise<string> {
	return wailsApp()!.StopProxyImportServer();
}

/** Saves data to disk via a native "Save As" dialog — the webview's
 *  `<a download>`/blob-URL trick has no browser chrome to catch downloads in
 *  Wails' Linux webkit backend, so it's a no-op there. Returns an error
 *  message on failure, or "" on success/cancel. */
export function saveFile(filename: string, base64Data: string): Promise<string> {
	return wailsApp()!.SaveFile(filename, base64Data);
}

/** Opens a URL in the user's default system browser. Plain `<a
 *  target="_blank">` clicks don't reliably escape Wails' webview (notably
 *  webkitgtk on Linux), so external links must go through this instead. */
export function openURL(url: string): void {
	wailsRuntime()!.BrowserOpenURL(url);
}

/** Svelte action for `<a target="_blank">` links to external sites: routes
 *  the click through {@link openURL} inside the Wails desktop build, and is
 *  a no-op everywhere else (the browser's normal navigation handles it). */
export function externalLink(node: HTMLAnchorElement) {
	if (!isWailsDesktop()) return;
	function onClick(e: MouseEvent) {
		e.preventDefault();
		openURL(node.href);
	}
	node.addEventListener("click", onClick);
	return {
		destroy() {
			node.removeEventListener("click", onClick);
		},
	};
}

/** Subscribes to raw chat-completion request bodies forwarded by the local
 *  import server (see proxyimport.go). Returns an unsubscribe function. */
export function onProxyImportReceived(
	handler: (raw: string) => void
): () => void {
	return wailsRuntime()!.EventsOn("proxy-import:received", (raw) =>
		handler(raw as string)
	);
}
