/** `window.go`/`window.runtime` only exist inside the Wails webview — a
 *  no-op check everywhere else (plain `pnpm dev`, tests, browsers), same
 *  idea as wailsConsoleForward.ts's `window.runtime` check.
 *
 *  These are hand-written wrappers around the Wails-injected globals rather
 *  than imports from the auto-generated `frontend/wailsjs/`: that directory
 *  is gitignored (regenerated by `wails build`/`wails dev`), but the Nix
 *  package builds the frontend with a plain `pnpm run build` that never
 *  invokes `wails generate`, so a build-time import from it would fail
 *  there even though `wails dev` works fine locally. */

interface WailsApp {
	StartProxyImportServer(): Promise<string>;
	StopProxyImportServer(): Promise<string>;
	IsProxyImportServerRunning(): Promise<boolean>;
}

interface WailsRuntime {
	EventsOn(
		eventName: string,
		callback: (...data: unknown[]) => void
	): () => void;
}

function wailsApp(): WailsApp | undefined {
	return (window as unknown as { go?: { main?: { App?: WailsApp } } }).go
		?.main?.App;
}

function wailsRuntime(): WailsRuntime | undefined {
	return (window as unknown as { runtime?: WailsRuntime }).runtime;
}

export function isWailsDesktop(): boolean {
	return typeof window !== "undefined" && !!wailsApp();
}

export function startProxyImportServer(): Promise<string> {
	return wailsApp()!.StartProxyImportServer();
}

export function stopProxyImportServer(): Promise<string> {
	return wailsApp()!.StopProxyImportServer();
}

/** Subscribes to raw chat-completion request bodies forwarded by the local
 *  import server (see proxyimport.go). Returns an unsubscribe function. */
export function onProxyImportReceived(
	handler: (raw: string) => void
): () => void {
	return wailsRuntime()!.EventsOn("proxy-import:received", (raw) =>
		handler(raw as string)
	);
}
